#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED
#define ERROR_EXCEDIDO_DIG_ENTEROS 1
#define ERROR_EXCEDIDO_DIG_FRACCIONARIOS 2
#define ERROR_EXCEDIDO_BASE_ORIGEN 3
#define ERROR_EXCEDIDO_BASE_DESTINO 4
#define ERROR_NUMERO_A_CONVERTIR_NO_ESPECIFICADO 5

#endif // CONSTANTES_H_INCLUDED
